runtime: nodejs16

env_variables:
  NODE_ENV: "production"
  MONGODB_URI: "your_mongodb_uri"
  JWT_SECRET: "your_jwt_secret"
  FIREBASE_CONFIG: "your_firebase_config"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
